### ISSUE TITLE
Says ANdroid on Windows Phone?

### ISSUE THREAD

**Issue by Pajservices** [anshuman91/device-detect#1]
I've just incorporated this into my WebApp - works fine - however when run ona Windows 8 phone it says that it's an Android?

` var DD = new DeviceDetect();
	    var isMobile = DD.isMobile;
	    var isDesktop = DD.isDesktop;
	    var isTablet = DD.isTablet;
   
	    // TO check device type and name
		
	    var MobileType = isMobile.any();
	    var y = isDesktop.any();
	    var z = isTablet.any();
		alert(MobileType +'/' + y + '/' + z);
	  
	  	if (MobileType === null) {
			alert ("I'm on a PC");
			
		}  else {
			
			alert ("I'm on a "+ MobileType);		
		}`

**Comment by anshuman91** [comment]
Fixed,

Please use below URL for latest script.
https://cdn.rawgit.com/anshuman91/device-detect/79b9374101da2f48d00724cd6dab5b109449274d/device-detect.min.js
